### PR TITLE
[issue 123] - Implement WildFly/EAP 8 Helm Charts provisioning differentiation

### LINKED ISSUE #123: Differentiate WildFly and EAP 8 Helm Charts provisioning
It is expected that Intersmash WildFly Helm Charts provisioning tooling supports EAP _latest_ (8 Beta ATM) as well.
Currently the implementation relies solely on the WIldFly Helm Charts values file schema in order to generate the Java model for a WildFly release. EAP 8 Helm Charts, though, have a different model.

This issue tracks the effort for to implement support for the test use cases that expect for one Intersmash provisioner to be able to provision both the community version of a service and its latest product equivalent.

---
* Environment: WildFly/EAP 8 Heml Charts provisioning
* Steps to reproduce: N/A

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
Backporting existing internal implementation

Fix #123 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [x] I have implemented unit tests to cover my changes
 - [x] I tested my code in OpenShift

### CODE REVIEW

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java [hunk 1]
```diff
@@ -55,20 +54,17 @@ public Map<String, String> getSetOverrides() {
...
-		} catch (Exception e) {
-			throw new RuntimeException(e);
-		}
+	private HelmChartRelease loadRelease() {
+		if (IntersmashTestsuiteProperties.isCommunityTestExecutionProfileEnabled()) {
+			return new WildFlyHelmChartReleaseAdapter(
+					HelmChartReleaseAdapter.<HelmWildflyRelease> fromValuesFile(
+							this.getClass().getResource("wildfly-helm-values.yaml"), HelmWildflyRelease.class));
+		} else if (IntersmashTestsuiteProperties.isProductizedTestExecutionProfileEnabled()) {
+			return new Eap8HelmChartReleaseAdapter(
```
Comment (tommaso-borgato) [inline testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java:63]: How can we fit channels info into a release loaded from a file? perhaps we need to use `Eap8HelmChartReleaseAdapter.withBuildEnvironmentVariables` ?

File: tools/intersmash-tools-provisioners/pom.xml [hunk 2]
```diff
@@ -233,6 +233,17 @@
                             <targetPackage>org.jboss.intersmash.model.helm.charts.values.wildfly</targetPackage>
                         </configuration>
                     </execution>
+                    <execution>
+                        <id>charts.values.generate-schema-model.eap8</id>
+                        <goals>
+                            <goal>generate</goal>
+                        </goals>
+                        <configuration>
+                            <sourceDirectory>${basedir}/src/main/resources/org/jboss/intersmash/tools/provision/helm/values/schema/eap8</sourceDirectory>
```
Comment (tommaso-borgato) [inline tools/intersmash-tools-provisioners/pom.xml:242]: personally I'd appreciate some comment reminding that file `eap8-helm-values.yaml` is actually from https://github.com/jbossas/eap-charts/blob/eap8/charts/eap8/values.schema.json

**Review by tommaso-borgato — APPROVED** [review]
LGTM, I just left  a couple of comments mostly about channels and their integration, which might be done in https://github.com/Intersmash/intersmash/pull/125

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartOpenShiftExampleApplication.java [hunk 3]
```diff
@@ -41,11 +42,15 @@ public class WildflyHelmChartOpenShiftExampleApplication
...
+			release = loadRelease(new Eap8HelmChartReleaseAdapter(new HelmEap8Release()));
+		} else
+			throw new IllegalStateException("Not a valid testing profile!");
 	}
 
-	private HelmWildflyRelease loadRelease() {
-		HelmWildflyRelease release = new HelmWildflyRelease();
+	private HelmChartRelease loadRelease(final WildflyHelmChartRelease release) {
 		// let's compute some additional maven args for our s2i build to happen on a Pod
 		String mavenAdditionalArgs = "-Denforcer.skip=true";
```
[the remark this answers is not in the document]
Comment (fabiobrz) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartOpenShiftExampleApplication.java:55]: Yep, this is where [WildflyDeploymentApplicationConfiguration](https://github.com/Intersmash/intersmash/blob/main/deployments/intersmash-deployments-provider/src/main/java/org/jboss/intersmash/deployments/WildflyDeploymentApplicationConfiguration.java) will help, hopefully.

File: tools/intersmash-tools-provisioners/pom.xml (hunk 2 above)
Comment (fabiobrz) [reply tools/intersmash-tools-provisioners/pom.xml:242]: +1, fixing.

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java (hunk 1 above)
Comment (fabiobrz) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java:63]: IIUC channels should be defined in the static file as well, or maybe I am not getting the point.
That being said though, after loading from a file, we could still manipulate the Helm release POJO dynamically in two different ways:
1. by using the schema POJO API, i.e. `HelmEap8Release`, since `HelmWildflyRelease` doesn't have one as it's not defined by its JSON schema.
2. by using the `WildflyHelmChartRelease`interface API, which both the `WildFlyHelmChartReleaseAdapter` and `Eap8HelmChartReleaseAdapter` implement, and specifically the following ones:
```
...
void setS2iChannels(LinkedHashSet<String> s2iFeaturePacks);

	WildflyHelmChartRelease withS2iChannels(LinkedHashSet<String> s2iChannels);

	WildflyHelmChartRelease withS2iChannel(String s2iChannel);
...
```

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesProvisionerTest.java [hunk 4]
```diff
@@ -39,7 +39,7 @@ public void basicProvisioningTest() {
 				.addSetOverride("build.uri", IntersmashConfig.deploymentsRepositoryUrl())
 				.addSetOverride("build.ref", IntersmashConfig.deploymentsRepositoryRef())
 				.addSetOverride("deploy.builderImage", application.getBuilderImage())
-				.addSetOverride("deployRuntimeImage", application.getRuntimeImage());
+				.addSetOverride("deploy.runtimeImage", application.getRuntimeImage());
```
[the remark this answers is not in the document]
Comment (fabiobrz) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesProvisionerTest.java:42]: Indeed, you're right. Must be coded differently according tio the specific chart documentation, i.e.:

- https://github.com/wildfly/wildfly-charts/blob/main/charts/wildfly/README.md
- https://github.com/jbossas/eap-charts/blob/eap8/charts/eap8/README.md

Fixing.

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java (hunk 1 above)
Comment (tommaso-borgato) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java:63]: I see `withS2iChannels` translates to in the EAP template, which in turn relies on variable GALLEON_PROVISION_CHANNELS to do its job:
```
      {{- if .Values.build.s2i.channels }}
      - name: GALLEON_PROVISION_CHANNELS
        value: {{ join "," .Values.build.s2i.channels | quote }}
      {{- end }}
```
any idea where `GALLEON_PROVISION_CHANNELS` is documented?

Comment (fabiobrz) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java:63]: Yep, that ENV VAR is documented for EAP 8 Beta, see the product [docs](https://access.redhat.com/documentation/it-it/red_hat_jboss_enterprise_application_platform/8-beta/html/using_jboss_eap_on_openshift_container_platform/assembly_capability-trimming-in-jboss-eap-for-openshift_default).

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesProvisionerTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (fabiobrz) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesProvisionerTest.java]: I decided to remove this setting which is best driven by the adapters that this PR introduces.
The example usage is still valid but just keeping the repo URL and branch overrides here.

File: tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/helm/wildfly/WildFlyHelmChartReleaseAdapter.java [hunk 5]
```diff
@@ -0,0 +1,703 @@
...
+	@Override
+	public BuildMode getBuildMode() {
+		return adaptee.getBuild() == null ? null
+				: adaptee.getBuild().getS2i() != null ? BuildMode.S2I
+						: adaptee.getBuild().getBootableJar() != null ? BuildMode.BOOTABLE_JAR : null;
+	}
+
+	@Override
+	public String getBootableJarBuilderImage() {
+		return adaptee.getBuild() == null ? ""
```
Comment (tommaso-borgato) [inline tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/helm/wildfly/WildFlyHelmChartReleaseAdapter.java:512]: @fabiobrz  I see the counterpart method Eap8HelmChartReleaseAdapter.getBootableJarBuilderImage() doesn't return anything on purpose: 
```java
	@Override
	public String getBootableJarBuilderImage() {
		// no Bootable JAR image is supported by EAP 8 Helm Charts
		return "";
	}
```
did I understand correctly we will have to implement one more adapter for XP5?

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java [hunk 6]
```diff
@@ -55,20 +54,17 @@ public Map<String, String> getSetOverrides() {
...
+					HelmChartReleaseAdapter.<HelmEap8Release> fromValuesFile(
+							this.getClass().getResource("eap8-helm-values.yaml"), HelmEap8Release.class));
```
Comment (tommaso-borgato) [inline testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java:65]: @fabiobrz since neither "wildfly-helm-values.yaml" nor "eap8-helm-values.yaml" define builder and runtime images (which are set in WildflyHelmChartOpenShiftExampleApplication.loadRelease) I suspect we should add such a setting to WildflyHelmChartExistingValuesOpenShiftExampleApplication.loadRelease in order to use the actual images passed to the test run, e.g.:

```java
	private HelmChartRelease loadRelease() {
		if (IntersmashTestsuiteProperties.isCommunityTestExecutionProfileEnabled()) {
			WildFlyHelmChartReleaseAdapter wildFlyHelmChartReleaseAdapter = return new WildFlyHelmChartReleaseAdapter(
					HelmChartReleaseAdapter.<HelmWildflyRelease> fromValuesFile(
							this.getClass().getResource("wildfly-helm-values.yaml"), HelmWildflyRelease.class));
			wildFlyHelmChartReleaseAdapter.setJdk17BuilderImage(...);
			wildFlyHelmChartReleaseAdapter.setJdk17RuntimeImage(...);
			return wildFlyHelmChartReleaseAdapter;
		} else if (IntersmashTestsuiteProperties.isProductizedTestExecutionProfileEnabled()) {
			Eap8HelmChartReleaseAdapter eap8HelmChartReleaseAdapter = new Eap8HelmChartReleaseAdapter(
					HelmChartReleaseAdapter.<HelmEap8Release> fromValuesFile(
							this.getClass().getResource("eap8-helm-values.yaml"), HelmEap8Release.class));
			eap8HelmChartReleaseAdapter.setJdk17BuilderImage(...);
			eap8HelmChartReleaseAdapter.setJdk17RuntimeImage(...);
			return eap8HelmChartReleaseAdapter;
		} else
			throw new IllegalStateException("Not a valid testing profile!");
	}
```

Comment (fabiobrz) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java:65]: +1 fixing

File: tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/helm/wildfly/WildFlyHelmChartReleaseAdapter.java (hunk 5 above)
Comment (fabiobrz) [reply tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/helm/wildfly/WildFlyHelmChartReleaseAdapter.java:512]: Well, it wouldn't seem the case to me, since the EAP Heml CHart should be valid for a bootable JAR build. That being said it actually depends on whether the developers would create yet another schema file.

File: testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java (hunk 6 above)
Comment (tommaso-borgato) [reply testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplication.java]: great!
