### PR TITLE
[issue-333] - Fix OpenDataHubOpenShiftOperatorProvisionerTest in order to properly remove created CRs

### LINKED ISSUE #333: Make OpenDataHubOpenShiftOperatorProvisionerTest clean up custom resources properly
When `OpenDataHubOpenShiftOperatorProvisionerTest` is run we noticed that the DSCInitialization resource that the test creates is not removed.

* Environment: testsuite/integration-tests
* Steps to reproduce: `mvn test -pl testsuite/integration-tests   -Pts.openshift -Dgroups=ts.ai -Dtest=OpenDataHubOpenShiftOperatorProvisionerTest -Dintersmash.test.excludedGroups.by.execution-profile=ts.not-for-community`

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description

Changes to properly handle the creation/deletion of CRs created by OpenDataHubOpenShiftOperatorProvisionerTest

Resolves #333 

---
**OpenShift CI checks (internal reference)**:
- **job**: eap-8.x-intersmash-integration-tests-community, **number**: 152 :white_check_mark: 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - **N/A** I have implemented unit tests to cover my changes
 - [x] I tested my code in OpenShift

### CODE REVIEW

File: provisioners/src/main/java/org/jboss/intersmash/provision/openshift/OpenShiftAIOpenShiftOperatorProvisioner.java [hunk 1]
```diff
@@ -47,7 +49,7 @@ public class OpenShiftAIOpenShiftOperatorProvisioner
 		// ... and common OpenShift provisioning logic, too
 		implements OpenShiftProvisioner<OpenShiftAIOperatorApplication> {
 
-	private static final String OPENSHIFT_OPERATORS_NAMESPACE = "openshift-operators";
+	private static final String OPENSHIFT_OPERATORS_NAMESPACE = "openshift-operators"; // --> redhat-ods-operator
```
Comment (tommaso-borgato) [inline provisioners/src/main/java/org/jboss/intersmash/provision/openshift/OpenShiftAIOpenShiftOperatorProvisioner.java]: this one could be a TODO or a separate issue about using the namespace mentioned in https://ai-on-openshift.io/odh-rhoai/gitops/#operator-installation

File: provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenDataHubOperatorProvisioner.java [hunk 2]
```diff
@@ -105,20 +112,25 @@ public void undeploy() {
...
-			deleted = deletionDetails.stream().allMatch(d -> d.getCauses().isEmpty());
-			if (!deleted) {
-				log.warn("Wasn't able to remove the 'DSCInitialization' resources created for '{}' instance!",
-						appName);
-			}
-			new SimpleWaiter(() -> dscInitializationClient().list().getItems().isEmpty()).level(Level.DEBUG).waitFor();
+		deletionDetails = dscInitializationClient().withName(appName).delete();
+		deleted = deletionDetails.stream().allMatch(d -> d.getCauses().isEmpty());
+		if (!deleted) {
+			log.warn("Wasn't able to remove the 'DSCInitialization' resources created for '{}' instance!",
```
Comment (tommaso-borgato) [inline provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenDataHubOperatorProvisioner.java]: have you checked if this warning is logged or not?

File: provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenShiftAIOperatorProvisioner.java [hunk 3]
```diff
@@ -105,16 +109,21 @@ public void undeploy() {
...
-			deleted = deletionDetails.stream().allMatch(d -> d.getCauses().isEmpty());
-			if (!deleted) {
-				log.warn("Wasn't able to remove the 'DSCInitialization' resources created for '{}' instance!",
-						appName);
-			}
-			new SimpleWaiter(() -> dscInitializationClient().list().getItems().isEmpty()).level(Level.DEBUG).waitFor();
+		deletionDetails = dscInitializationClient().delete();
+		deleted = deletionDetails.stream().allMatch(d -> d.getCauses().isEmpty());
+		if (!deleted) {
+			log.warn("Wasn't able to remove the 'DSCInitialization' resources created for '{}' instance!",
```
Comment (tommaso-borgato) [inline provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenShiftAIOperatorProvisioner.java]: have you checked if this warning is logged or not? in my tests the resource can't be deleted because of the **finalizer**:
```
$ oc get DSCInitialization/default-dsci --all-namespaces 
NAME           AGE    PHASE         CREATED AT
default-dsci   3h9m   Progressing   2025-12-03T08:13:30Z
```
we might have to patch and remove **finalizer**s before deleting...

File: provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenDataHubOperatorProvisioner.java (hunk 2 above)
Comment (fabiobrz) [reply provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenDataHubOperatorProvisioner.java]: Actually not logged, since the removal works.

File: provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenShiftAIOperatorProvisioner.java (hunk 3 above)
Comment (fabiobrz) [reply provisioners/src/main/java/org/jboss/intersmash/provision/operator/OpenShiftAIOperatorProvisioner.java]: Not really, patching finalizers is a last resort choice and only done manually when something's gone wrong previously. Here there's no need to do so since the workflow seems to be clean now.
